sudo: required

language: c

os:
  - linux

compiler:
  - gcc

before_script:
  - git clone https://github.com/jedisct1/libsodium.git --branch=stable
  - cd libsodium
  - env CPPFLAGS=-DED25519_NONDETERMINISTIC ./configure --disable-dependency-tracking
  - make -j$(nproc)
  - sudo make install
  - sudo ldconfig
  - cd ..

script:
  - rm -fr build
  - mkdir build
  - cd build
  - cmake ..
  - make -j$(nproc)
  - cd ..

  - rm -fr build
  - mkdir build
  - cd build
  - cmake -D STATIC_LIBSODIUM=1 ..
  - make -j$(nproc)
  - cd ..

  - rm -fr build
  - mkdir build
  - cd build
  - cmake -D BUILD_STATIC_EXECUTABLES=1 ..
  - make -j$(nproc)
  - cd ..

matrix:
  - fast_finish: true
